# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.31
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _cchardet
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


CHARDET_RESULT_OK = _cchardet.CHARDET_RESULT_OK
CHARDET_RESULT_NOMEMORY = _cchardet.CHARDET_RESULT_NOMEMORY
CHARDET_RESULT_INVALID_DETECTOR = _cchardet.CHARDET_RESULT_INVALID_DETECTOR
CHARDET_ENCODING_ISO_2022_JP = _cchardet.CHARDET_ENCODING_ISO_2022_JP
CHARDET_ENCODING_ISO_2022_CN = _cchardet.CHARDET_ENCODING_ISO_2022_CN
CHARDET_ENCODING_ISO_2022_KR = _cchardet.CHARDET_ENCODING_ISO_2022_KR
CHARDET_ENCODING_ISO_8859_5 = _cchardet.CHARDET_ENCODING_ISO_8859_5
CHARDET_ENCODING_ISO_8859_7 = _cchardet.CHARDET_ENCODING_ISO_8859_7
CHARDET_ENCODING_ISO_8859_8 = _cchardet.CHARDET_ENCODING_ISO_8859_8
CHARDET_ENCODING_BIG5 = _cchardet.CHARDET_ENCODING_BIG5
CHARDET_ENCODING_GB18030 = _cchardet.CHARDET_ENCODING_GB18030
CHARDET_ENCODING_EUC_JP = _cchardet.CHARDET_ENCODING_EUC_JP
CHARDET_ENCODING_EUC_KR = _cchardet.CHARDET_ENCODING_EUC_KR
CHARDET_ENCODING_EUC_TW = _cchardet.CHARDET_ENCODING_EUC_TW
CHARDET_ENCODING_SHIFT_JIS = _cchardet.CHARDET_ENCODING_SHIFT_JIS
CHARDET_ENCODING_IBM855 = _cchardet.CHARDET_ENCODING_IBM855
CHARDET_ENCODING_IBM866 = _cchardet.CHARDET_ENCODING_IBM866
CHARDET_ENCODING_KOI8_R = _cchardet.CHARDET_ENCODING_KOI8_R
CHARDET_ENCODING_MACCYRILLIC = _cchardet.CHARDET_ENCODING_MACCYRILLIC
CHARDET_ENCODING_WINDOWS_1251 = _cchardet.CHARDET_ENCODING_WINDOWS_1251
CHARDET_ENCODING_WINDOWS_1252 = _cchardet.CHARDET_ENCODING_WINDOWS_1252
CHARDET_ENCODING_WINDOWS_1253 = _cchardet.CHARDET_ENCODING_WINDOWS_1253
CHARDET_ENCODING_WINDOWS_1255 = _cchardet.CHARDET_ENCODING_WINDOWS_1255
CHARDET_ENCODING_UTF_8 = _cchardet.CHARDET_ENCODING_UTF_8
CHARDET_ENCODING_UTF_16BE = _cchardet.CHARDET_ENCODING_UTF_16BE
CHARDET_ENCODING_UTF_16LE = _cchardet.CHARDET_ENCODING_UTF_16LE
CHARDET_ENCODING_UTF_32BE = _cchardet.CHARDET_ENCODING_UTF_32BE
CHARDET_ENCODING_UTF_32LE = _cchardet.CHARDET_ENCODING_UTF_32LE
CHARDET_ENCODING_HZ_GB_2312 = _cchardet.CHARDET_ENCODING_HZ_GB_2312
CHARDET_ENCODING_X_ISO_10646_UCS_4_3412 = _cchardet.CHARDET_ENCODING_X_ISO_10646_UCS_4_3412
CHARDET_ENCODING_X_ISO_10646_UCS_4_2143 = _cchardet.CHARDET_ENCODING_X_ISO_10646_UCS_4_2143
CHARDET_ENCODING_ISO_8859_2 = _cchardet.CHARDET_ENCODING_ISO_8859_2
CHARDET_ENCODING_WINDOWS_1250 = _cchardet.CHARDET_ENCODING_WINDOWS_1250
CHARDET_ENCODING_TIS_620 = _cchardet.CHARDET_ENCODING_TIS_620
chardet_create = _cchardet.chardet_create
chardet_destroy = _cchardet.chardet_destroy
chardet_handle_data = _cchardet.chardet_handle_data
chardet_data_end = _cchardet.chardet_data_end
chardet_reset = _cchardet.chardet_reset
chardet_get_charset = _cchardet.chardet_get_charset


