# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.31
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _cchardet
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


CHARDET_RESULT_OK = _cchardet.CHARDET_RESULT_OK
CHARDET_RESULT_NOMEMORY = _cchardet.CHARDET_RESULT_NOMEMORY
CHARDET_RESULT_INVALID_DETECTOR = _cchardet.CHARDET_RESULT_INVALID_DETECTOR
chardet_create = _cchardet.chardet_create
chardet_destroy = _cchardet.chardet_destroy
chardet_handle_data = _cchardet.chardet_handle_data
chardet_data_end = _cchardet.chardet_data_end
chardet_reset = _cchardet.chardet_reset
chardet_get_charset = _cchardet.chardet_get_charset


